services:
  game_pps_back:
    container_name: game_pps_back
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - game_pps_back_db
    environment:
      - DATABASE_URL=${DOCKER_DATABASE_URL}
      - FLASK_ENV=development
      - FLASK_APP=run.py
    command: flask run --host=0.0.0.0

  game_pps_back_db:
    container_name: game_pps_back_db
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: